spring:
  application:
    name: hello-spring-cloud-web-feign
server:
  port: 8766
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true

